theme: minima
title: KleberDotNet's GitHub Pages Blog
author: KleberDotNet
email: kleberkelvyn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  As I learn more about GitHub pages, a robot powered tutorial assists me in creating this blog.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  KleberDotNet # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
